---

- name: Setup Variables for CentOS 7
  set_fact:
    target_ans_user: "centos"
  when: (osselection == "centos7")

- name: Setup Variables for CentOS 8
  set_fact:
    target_ans_user: "centos"
  when: (osselection == "centos8")

- name: Setup Variables for RHEL 7
  set_fact:
    target_ans_user: "ec2-user"
  when: (osselection == "rhel7")

- name: Setup Variables for RHEL 8
  set_fact:
    target_ans_user: "ec2-user"
  when: (osselection == "rhel8")

- name: Setup Variables for Windows
  set_fact:
    target_ans_user: "Administrator"
  when: (osselection == "win2019") or (osselection == "win2022")
