---

- name: Set US DNS Servers in Windows
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    - 10.251.2.156
    - 10.251.5.163
  when: (region == "us-east-1")

- name: Set CA DNS Servers in Windows
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    - 161.108.208.253
    - 161.108.90.67
    - 161.108.208.240
  when: (region == "ca-central-1")
